build_script:
  - ps: (new-object net.webclient).DownloadFile("http://s3.amazonaws.com/julialang/bin/winnt/x64/0.3/julia-0.3.0-prerelease-win64.exe", "C:\projects\julia-binary.exe")
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

test_script:
  - cd C:\projects\julia\share\julia\test
  - C:\projects\julia\bin\julia.exe runtests.jl all
